workflows:
  ios-build:
    name: Cordova iOS Build

    environment:
      node: 20

    scripts:
      - npm install
      - npm install -g cordova
      - cordova platform rm ios || true
      - cordova platform add ios
      - cordova prepare ios
      - cordova build ios --release

    artifacts:
      - platforms/ios/**/*.ipa
      - platforms/ios/**/*.xcarchive
      - platforms/ios/build/**/*.app